// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApp.Data.Data;

#nullable disable

namespace RecipeApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329011142_SeedIngredients")]
    partial class SeedIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("RecipeApp.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CaloriesPerUnit")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPerUnit = 18f,
                            Description = "Tomate fraîche",
                            Name = "Tomate",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPerUnit = 364f,
                            Description = "Farine de blé",
                            Name = "Farine",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPerUnit = 70f,
                            Description = "Oeuf frais",
                            Name = "Oeuf",
                            Unit = "pièce"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPerUnit = 120f,
                            Description = "Huile d'olive extra vierge",
                            Name = "Huile d'olive",
                            Unit = "cuillère"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPerUnit = 165f,
                            Description = "Blanc de poulet",
                            Name = "Poulet",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPerUnit = 130f,
                            Description = "Riz blanc cuit",
                            Name = "Riz",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPerUnit = 42f,
                            Description = "Lait entier",
                            Name = "Lait",
                            Unit = "100ml"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPerUnit = 387f,
                            Description = "Sucre blanc",
                            Name = "Sucre",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPerUnit = 12f,
                            Description = "Concombre frais",
                            Name = "Concombre",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPerUnit = 402f,
                            Description = "Fromage à pâte dure",
                            Name = "Fromage",
                            Unit = "100g"
                        });
                });

            modelBuilder.Entity("RecipeApp.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeApp.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("RecipeApp.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeApp.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeApp.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApp.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("RecipeApp.Data.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
